version: '3'

services:
  dev-mode:
    extends:
      file: docker-compose.yml
      service: rest-variantvalidator
    depends_on:
      - rv-vdb
      - rv-vvta
      - rv-seqrepo
    volumes:
      - rest_vv_dev_volume:/app
      - vv-logs:/usr/local/share/logs  # Mount volume for logs
      - seqdata:/usr/local/share/seqdata  # Mount volume for sequence data
    ports:
      - "5001:5000"
      - "5050:5050"
      - "8000:8000"
      - "9000:9000"
    expose:
      - "5001"  # Expose ports for external access
      - "5050"
      - "8000"
      - "8080"

volumes:
  rest_vv_dev_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}'
  seqdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/variantvalidator_data/seqdata'
  vv-logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/variantvalidator_data/logs'

